# Pandas - Group by and Aggregating

In [1]:
# importing pandas library

import pandas as pd

In [2]:
# reading csv file

df = pd.read_csv("https://raw.githubusercontent.com/lncgthb/Python-Learnings/refs/heads/main/Python%20Pandas/Datasets/3.%20Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [3]:
# grouping by "base flavor" and identifying the average

group_by_frame = df.groupby('Base Flavor')

In [4]:
group_by_frame.mean(numeric_only = True)  # python update - we need to put numeric_only = True on the function MEAN

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [5]:
# or aggreagate within the groupby (average or mean)

df.groupby("Base Flavor").mean(numeric_only = True)

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate              8.4        7.233333         15.70
Vanilla                5.7        5.650000         11.35

In [6]:
# or aggreagate within the groupby (count)

df.groupby("Base Flavor").count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [7]:
# or aggreagate within the groupby (min)

df.groupby("Base Flavor").min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [8]:
# or aggreagate within the groupby (max)

df.groupby("Base Flavor").max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [9]:
# or aggreagate within the groupby (sum)

sum1 = df.groupby("Base Flavor").sum()


# the updated python summed the string so we need to drop string column datas

sum1.drop(columns = ["Flavor", "Liked"])

             Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate             25.2            21.7          47.1
Vanilla               34.2            33.9          68.1

In [10]:
# official "aggragate function" by using "dictionaries" with "list" in it

df.groupby("Base Flavor").agg({"Flavor Rating" : ["mean", "max", "count", "sum"], "Texture Rating" : ["mean", "max", "count", "sum"]})

            Flavor Rating                   Texture Rating
                     mean   max count   sum           mean  max count   sum
Base Flavor
Chocolate             8.4   8.8     3  25.2       7.233333  7.6     3  21.7
Vanilla               5.7  10.0     6  34.2       5.650000  8.0     6  33.9

In [11]:
# GROUP ON MULTIPLE COLUMNS
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [12]:
# GROUP ON MULTIPLE COLUMNS and identifying "mean"

df.groupby(["Base Flavor", "Liked"]).mean(numeric_only = True)

                   Flavor Rating  Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              8.4        7.233333     15.700000
Vanilla     No               3.6        4.466667      8.066667
            Yes              7.8        6.833333     14.633333

In [13]:
# GROUP ON MULTIPLE COLUMNS and using aggregate function with dictionary with a list

df.groupby(["Base Flavor", "Liked"]).agg({"Flavor Rating" : ["mean", "max", "count", "sum"]})

                  Flavor Rating
                           mean   max count   sum
Base Flavor Liked
Chocolate   Yes             8.4   8.8     3  25.2
Vanilla     No              3.6   4.7     3  10.8
            Yes             7.8  10.0     3  23.4

In [14]:
# shortcut generalize function

df.groupby("Base Flavor").describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]